package com.demo.interview.xiecheng;

import java.util.Scanner;

/**
 * @Author Jusven
 * @Date 2021/4/15 19:10
 * 假设在一条无限长的道路上盖房子，第一个月在某个点盖一个红房子，之后每个月，都会在上一次盖的新房子的左边盖一个绿房子，
 *
 * 右边盖一个红房子。（假设两个房子之间的空间无限大，可以一直在中间盖房子）
 *
 * 用字符'R'表示红房子，用字符'G'表示绿房子。
 *
 * 输入一个n(1≤n≤12)，表示过了n个月，打印出当前道路上房子从左到右的排列。
 *
 * 要求：
 *
 * 1.    当输入非数字,输出：N
 *
 * 2.    当输入数字超出限制时，输出O
 *
 * 样例：
 *
 * 输入1
 *
 * 输出 R
 *
 * 输入2
 *
 * 输出 GRR
 *
 * 输入3
 *
 * 输出 GGRRGRR
 *
 * 输入5
 *
 * 输出 GGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR
 *
 */
public class demo1 {  //91%
    static String buildingHouse(String n) {
        //遍历
        for (int i = 0; i < n.length(); i++) {
            if(n.charAt(i)>'9' || n.charAt(i)<'0')
                return "N";
//            if(!Character.isDigit(n.charAt(i))){  //字符是否为数字
//                return "N";
//            }
        }
        int num = Integer.parseInt(n);
        if(num<1||num>12)
            return "O";
        String[] arr = new String[num];
        arr[0] = "R";
//        String str1 = "R";
//        String s = "R";
//        String str2 = "G"+str1+"R";
        for (int i = 1; i <num ; i++) {
//            String temp = arr[i-1];
            arr[i] = buildingHouse2(arr[i-1],arr[i-1].length());
        }
        StringBuilder sb =new StringBuilder();
        sb.append("GGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR");
        String s = "GGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRGGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRGGGRGGRRRGGRRGRRRGGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
        String s2 ="GGRGGRRGGGRRGRRRGGRGGRRRGGRRGRR";
        return arr[num-1];
    }
    static String buildingHouse2(String str,int n) {
        String[] arr_str = str.split("");
        String s = "";
        for (int i = 0; i <n ; i++) {
            if(i%2==0){
                s = s + "G"+arr_str[i]+"R";
            }else{
                s = s + arr_str[i];
            }
        }
        return s;
    }


    /******************************结束写代码******************************/


    public static void main(String[] args){
        Scanner in = new Scanner(System.in);
        String res;

        String _n;
        try {
            _n = in.nextLine();
        } catch (Exception e) {
            _n = null;
        }

        res = buildingHouse(_n);
        System.out.println(res);
    }
}
